### ISSUE TITLE
DeltaToAxis cursor still visible

### ISSUE THREAD

**Issue by machomuchacho** [HidWizards/UCR-Plugins#12]
Hi, I don't know if this is normal or not but when I use DeltaToAxis to convert mouse to a joystick, it works but I can still see the cursor moving on the screen. I know how I can hide it, but simply "hiding" it doesn't solve my problem since it's still here, I'm trying to play PS Now games so even if I find a way to hide it and trap it in the middle of the screen at the same time, it's not ok because the PS Now overlay will still show up. I need something that can disable the cursor and read raw input data from my mouse, Is it possible with this addon ? If no, how can I do ?

Thanks,

**Comment by evilC** [comment]
https://github.com/Snoothy/UCR/wiki/Core_Interception#blocking-with-interception

**Comment by machomuchacho** [comment]
Yeah, so I enabled blocking but the thing is that it blocks instantly and I can't switch windows...

**Comment by evilC** [comment]
It does mention that in the documentation, you would need a 2nd mouse

**Comment by machomuchacho** [comment]
I'm on a laptop so I have my touch pad but will there be any updates in the future to fix this problem ?

**Comment by evilC** [comment]
It's something I would like to address, yeah. Something like a plugin that lets you assign an input which deactivates the profile

**Comment by machomuchacho** [comment]
This is what I was thinking about. Hope it will come soon.
