### ISSUE TITLE
DeltaToAxis missing invert option

### ISSUE THREAD

**Issue by evilC** [HidWizards/UCR-Plugins#6]

**Comment by norstbox** [comment]
> Need to invert Y axis output, and dont see any option

@94d33m, actually, you don't need dedicated "invert option". Negative "Relative Sensitivity" will do the trick (i.e. modify 100 -> -100).

**Comment by OLLYDOTDEV** [comment]
> > Need to invert Y axis output, and dont see any option
> 
> @94d33m, actually, you don't need dedicated "invert option". Negative "Relative Sensitivity" will do the trick (i.e. modify 100 -> -100).

thanks that did the trick
